backend:
  name: git-gateway
  branch: main
media_folder: "/assets/uploads"
show_preview_links: true
collections:
  - name: "settings"
    label: "Settings"
    editor: { preview: false }
    files:
      - file: "_data/settings.json"
        name: "settings"
        label: "Site Settings"
        fields:
          - label: "About text"
            name: "about_copy"
            widget: "markdown"
            required: false
            buttons: [bold, italic, link, bulleted-list, numbered-list, heading-two]
            editor_components: []
          - label: "Ticket Link"
            name: "ticket_link"
            widget: "string"
            required: false
          - label: "Meta Title"
            name: "meta_title"
            widget: "string"
            hint: "Will be appear as the title in search results and social media cards."
            required: false
          - label: "Meta Description"
            name: "meta_description"
            widget: "string"
            hint: "Might appear in search results and social media cards."
            required: false
          - label: "Default Social Media Image"
            name: "social_image"
            required: false
            widget: "image"
            hint: "Will appear in social media cards. On project pages the featured image will be used instead."
  - name: "projects"
    label: "Projects"
    label_singular: "Project"
    editor: { preview: false }
    folder: "projects/"
    preview_path: "/projects/{{slug}}/"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "project"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Project Title"
        name: "project_title"
        widget: "string"
        required: false
      - label: "Betreuender Prof"
        name: "prof"
        widget: "string"
        required: false
      - label: Is this a draft?
        name: draft
        widget: boolean
        default: true
        hint: "Draft projects won't appear on the homepage, but can still be accessed through a direct link.
          "
      - label: "Tags"
        name: "tags"
        widget: "list"
        hint: "Separate multiple tags by comma."
        required: false
      - label: "Description"
        name: "body"
        widget: markdown
        required: false
        buttons: [bold, italic, link, bulleted-list, numbered-list]
        editor_components: []
      - label: Links
        name: links
        required: false
        max: 5
        label_singular: link
        widget: list
        summary: url
        fields:
          - label: URL
            name: url
            widget: string
      - label: Gallery Images
        label_singular: Gallery Image
        name: gallery
        widget: list
        required: false
        max: 10
        fields:
          - label: Image file
            name: image
            widget: image
            media_library:
              config:
                max_file_size: 5000000
          - label: Alt text
            name: alt
            widget: string
      - label: Featured Image
        required: false
        name: featured_image
        widget: object
        summary: "{{fields.url}}"
        fields:
          - label: Image file
            name: image
            widget: "image"
            media_library:
              config:
                max_file_size: 5000000
          - label: Alt text
            name: alt
            widget: "string"
